version: '3.7'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  musicashram:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./package.json:/usr/src/app/package.json
    container_name: musicashram
    expose:
      - '3005'
    ports:
      - '3005:3005'
    command: yarn run dev
    environment:
      - 'DATABASE_URL=${DATABASE_URL}'
volumes:
  postgres: